modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPLv3"

[[mods]]
modId="exdeorum"
version="${mod_version}"
displayName="Ex Deorum"
credits="Herobrine knows all. Thanks to Erasmus_Crowley for the original 1.7 mod"
authors="TheDarkColour"
description='''
Bringing back the original Ex Nihilo.
'''
[[dependencies.exdeorum]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exdeorum]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"
